### ISSUE TITLE
Eigen's commit history with git-remote-hg

### ISSUE THREAD

**Issue by pretyman** [hunter-packages/eigen#1]
Hi @ruslo ,

I see that the commit logs for Eigen were not preserved in this repository. I cherry-pick'ed your patch onto 3.3-beta1 as I needed a linear solver not available in 3.2.4 which is currently in hunter-packages.

My question is: if we end up having more patches in this repo, wouldn't it be easier to rebase the patches onto Eigen instead of cherry-picking? Maybe my understanding is wrong about cherry-picking, but cherry-picking would work by selecting each commit individually and applying the changes to it, where rebasing we would apply them all in one go.

I ask because I used the `git-remote-hg` ( https://github.com/fingolfin/git-remote-hg ) script to download Eigen's sources and apply your patch, thinking there would be a benefit in doing so. And that will cause to have a different master in my local repo from the one in hunter-packages. 

Does keeping the commit history make any sense in the point of view of hunter-packages?

I'm not sure that the beta1 version should go into the `cmake/config/default.cmake` though

Thanks

**Comment by ruslo** [comment]
> I see that the commit logs for Eigen were not preserved in this repository

I just choosed the easy way since there was no git repository. Mercurial -> Git converter would be nice, but as far as I understand it works very good in case you are **moving** from hg to git. But if upstream  still will use hg it may be tricky (?). If you know how to manage this stuff please do it.

> I'm not sure that the beta1 version should go into the cmake/config/default.cmake though

Up to @hunter-packages/eigen team.

**Comment by pretyman** [comment]
>  If you know how to manage this stuff please do it.

Well, this is the first time I'm trying it out, it wouldn't hurt to have a first time experience. I guess I'll only get to know if it works well in the next update.

**Comment by ruslo** [comment]
@pretyman I have experience of using svn -> git converted repo when Boost was changing vcs. The problem about it is that every time you run converter you got completely new history. So effectively updating repo is like merging two non-related projects. So every my update was ending with resolving conflicts which was not related to my patches.

**Comment by ruslo** [comment]
Closing inactive discussion.
