### ISSUE TITLE
add hunter-429aa5254200

### ISSUE THREAD

**Issue by headupinclouds** [hunter-packages/eigen#10]
@NeroBurner : I'd like to add release for a specific upstream Eigen commit to support the tensorflow effort.  I've created a branch for this in my fork here https://github.com/headupinclouds/eigen/tree/hunter-429aa5254200 .  I don't believe there is a way to do this via pull request.  I'm using hunter-429aa5254200 since 429aa5254200 is the commit used in the upstream bazel build files (there is no tag/release).  It seems like a reasonable convention, although we could also update the main hunter branch and just use an archive URL referencing the commit as discussed here: https://github.com/ruslo/hunter/issues/1188#issuecomment-343775509

**Comment by ruslo** [comment]
Released: https://github.com/hunter-packages/eigen/releases/tag/hunter-429aa5254200-p0
